[package]
name = "web-server"
version = "0.1.0"
authors = ["kacejot <kacejot@fex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.0"
mime = "0.2.3"
router = "0.6.0"
urlencoded = "0.6.0"