[package]
name = "procedural-terrain-generation"
version = "0.1.0"
authors = ["kacejot <kacejot@fex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
rand = "0.7.2"
image = "0.22.2"