[package]
name = "greatest-common-divisor"
version = "0.1.0"
authors = ["kacejot <kacejot@fex.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "greatest-common-divisor"
path = "main.rs"
